'use client'

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react'

export type Currency = 'TRY' | 'USD' | 'EUR'
export type Language = 'tr' | 'en'

interface Rates {
  USD: number
  EUR: number
}

interface SettingsContextType {
  currency: Currency
  setCurrency: (c: Currency) => void
  language: Language
  setLanguage: (l: Language) => void
  rates: Rates
  formatPrice: (priceInTry: number) => string
  t: (key: string, defaultText?: string) => string
}

const defaultRates: Rates = {
  USD: 38.5,
  EUR: 42.0
}

const SettingsContext = createContext<SettingsContextType | undefined>(undefined)

const translations: Record<Language, Record<string, string>> = {
  tr: {
    'topbar.announcement': '✦ %100 FİZİKSEL EKSPERTİZ & İSTANBUL İÇİ AYNI GÜN MASAÜSTÜ TESLİMAT',
    'topbar.announcement1': '✦ %100 FİZİKSEL EKSPERTİZ & 3D SPEKTRAL ANALİZ GARANTİSİ',
    'topbar.announcement2': '⚡ İSTANBUL İÇİ 4 SAATTE ÖZEL VIP KURYE İLE MASAÜSTÜ TESLİMAT',
    'topbar.announcement3': '🛡️ PEONY LAB™ SERTİFİKALI VE HUKUKİ GARANTİLİ ARŞİV KOLEKSİYONU',
    'topbar.vipBadge': 'PEONY CONCIERGE™',
    'topbar.whatsapp': 'VIP DESTEK HATTI',
    'nav.howItWorks': 'NASIL ÇALIŞIR?',
    'nav.myPanel': 'PANELİM',
    'nav.myOrders': 'SİPARİŞLERİM',
    'nav.sell': 'SATIŞ YAP',
    'nav.myAccount': 'HESABIM',
    'nav.login': 'GİRİŞ',
    'nav.logout': 'ÇIKIŞ',
    'nav.allProducts': 'TÜM ÜRÜNLER',
    'nav.women': 'KADIN',
    'nav.men': 'ERKEK',
    'nav.kids': 'ÇOCUK',
    'nav.accessories': 'AKSESUAR',
    'nav.newArrivals': 'YENİ GELENLER',
    'nav.collection': 'Koleksiyon',
    'nav.cart': 'Sepet',
    'nav.addToCart': 'SEPETE EKLE',
    'nav.vipOffers': 'VIP Teklifler',
    'nav.brands': 'MARKALAR',
    'nav.userServices': 'KULLANICI SERVİSLERİ',
    'nav.account': 'HESAP',
    'nav.messages': 'MESAJLARIM',
    'nav.settings': 'HESAP AYARLARIM',
    'hero.title': 'LÜKSÜN EN SAF VE DÖNGÜSEL HALİ',
    'hero.subtitle': 'Uzman onaylı, sertifikalı ve orijinalliği %100 garanti altındaki ikinci el arşiv parçaları.',
    'hero.explore': 'KOLEKSİYONU KEŞFET',
    'hero.consign': 'LÜKSÜ NAKDE ÇEVİR',
    'hero.tagline': 'MİRASIN YENİ SAHİBİ',
    'category.bags': 'Çanta',
    'category.clothing': 'Kıyafet',
    'category.shoes': 'Ayakkabı',
    'category.accessories': 'Aksesuar',
    'category.outerwear': 'Dış Giyim',
    'category.topwear': 'Üst Giyim',
    'category.bottomwear': 'Alt Giyim',
    'category.dress': 'Elbise',
    'category.girls': 'Kız Çocuk',
    'category.boys': 'Erkek Çocuk',
    'category.scarf': 'Eşarp',
    'category.bracelet': 'Bileklik',
    'category.foulard': 'Fular',
    'category.hat': 'Şapka',
    'category.belt': 'Kemer',
    'category.glasses': 'Gözlük',
    'category.wallet': 'Cüzdan',
    'category.jewelry': 'Takı',
    'product.buy': 'SATIN AL',
    'product.offer': 'TEKLİF VER',
    'product.sold': 'BU PARÇA SATILMIŞTIR',
    'product.condition': 'KONDİSYON',
    'product.year': 'SATIN ALINDIĞI YIL',
    'product.seller': 'SATICI',
    'product.dimensions': 'BOYUTLAR',
    'product.expertReport': 'PEONY UZMAN RAPORU',
    'weather.title': '📍 PEONY WEATHER CONCIERGE',
    'weather.subtitle': 'Konumunuza Özel Stil Önerileri',
    'manifesto.title': 'Sadece bir ürün değil, bir miras devrediyorsunuz.',
    'manifesto.desc': 'Peony Collective\'de lüks sadece bir etiket değil, bir güvencedir. Uzman küratörlerimiz ve laboratuvar hassasiyetindeki ekspertiz sürecimizle, orijinallik artık bir soru işareti değil, garantidir.',
    'metric.portfolioValue': 'Portföy Değeri',
    'metric.portfolioSub': 'Onaylı & Bekleyen',
    'metric.counterfeit': 'Sahte Ürün',
    'metric.counterfeitSub': 'Kuruluşumuzdan Bugüne',
    'metric.controlPoints': 'Kontrol Noktası',
    'metric.controlSub': 'Fiziksel Ekspertiz',
    'metric.approval': 'Ortalama Onay',
    'metric.approvalSub': 'Hızlı İşlem Süresi',
    'metric.hours': 'SA',
    'curated.seasonal': 'Mevsimsel Seçki',
    'curated.smart': 'Akıllı Lüks (15.000 ₺ Altı)',
    'curated.summerTitle': 'Yaz İndirimi: Zıtlıkların Uyumu',
    'curated.summerDesc': 'Lüks, gündelik konfor ile arzunun en üst zirvesini buluşturur. Sahilde adımlarınıza eşlik edecek en şık terliklerden, davetlerin en sofistike yıldızı Kelly çantalara uzanan zıt kutuplar bir arada.',
    'curated.explore': 'Seçkiyi İncele →',
    'home.shopByCategory': 'Kategorilere Göre Alışveriş Yapın',
    'home.allCollection': 'TÜM KOLEKSİYON',
    'home.beachVibe': 'PLAJ ŞIKLIĞI ⛵',
    'home.cityBreeze': 'ŞEHİR ESİNTİSİ 🏙️',
    'home.eveningEvent': 'GECE DAVETİ 🍸',
    'home.allGenders': 'TÜM CİNSİYETLER',
    'home.allBrands': 'TÜM MARKALAR',
    'trust.standards': 'PEONY STANDARDS',
    'trust.title': 'Güven Zinciri & Ekspertiz',
    'trust.tabHow': 'NASIL ÇALIŞIR?',
    'trust.tabLab': 'PEONY LAB & ENTRUPY',
    'trust.tabCert': 'ORİJİNALLİK SERTİFİKASI',
    'trust.tabStories': 'OBJELERİN HİKAYESİ',
    'trust.step1Title': 'Satıcı Başvurur',
    'trust.step1Desc': 'Ürününü fotoğraflayıp platforma yükler. Fiyat önerisi alır.',
    'trust.step2Title': 'Escrow & Kurye',
    'trust.step2Desc': 'Alıcı ödemesi bloke edilir. Özel kurye ürünü satıcıdan alır.',
    'trust.step3Title': 'Lab Ekspertizi',
    'trust.step3Desc': '32 nokta fiziksel + Entrupy teknoloji doğrulaması yapılır.',
    'trust.step4Title': 'Teslimat & Ödeme',
    'trust.step4Desc': 'Onaylı ürün alıcıya gider, satıcı ödemesini alır.',
    'partner.tagline': 'PARTNER WITH PEONY',
    'partner.title': 'Lüksü Nakde Çevirin',
    'partner.tabSupplier': 'KURUCU TEDARİKÇİ PROGRAMI (%0)',
    'partner.tabVip': 'PEONY VIP (CONCIERGE)',
    'partner.launchTag': 'ÖZEL LANSMAN AVANTAJI',
    'partner.commissionTitle': '%0\'dan Başlayan Komisyon Oranları',
    'partner.commissionDesc': 'Peony lansman dönemine özel sınırlı sayıdaki kurucu tedarikçiden biri olun, lüks parçalarınızı en yüksek değerle ve komisyonsuz avantajlarla nakde çevirin.',
    'partner.applyBtn': 'HEMEN BAŞVUR',
    'partner.treasureTag': 'UNLOCK YOUR WARDROBE\'S VALUE',
    'partner.treasureTitle': 'Kullanmadığınız lüks, başkası için bir hazine.',
    'partner.sellNowBtn': 'HEMEN SATIŞ YAP',
    'footer.tagline': 'Mirasın Yeni Sahibi',
    'footer.aboutText': 'Yarım milyonluk bir yatırımı şansa bırakamazsınız. Peony Collective, her parçayı 32 noktalı fiziksel ekspertiz ve 3D Spektral Analizden geçirerek orijinalliğini garantiler.',
    'footer.legalTitle': 'YASAL BELGELER',
    'footer.terms': 'Kullanım Koşulları',
    'footer.privacy': 'Gizlilik Politikası',
    'footer.kvkk': 'KVKK Aydınlatma Metni',
    'footer.distanceSales': 'Mesafeli Satış Sözleşmesi',
    'footer.preInfo': 'Ön Bilgilendirme Formu',
    'footer.returnPolicy': 'İptal ve İade Koşulları',
    'footer.delivery': 'Teslimat ve Kargo Politikası',
    'footer.privateListTitle': 'PRIVATE LIST',
    'footer.privateListDesc': 'Özel kürasyonlardan, gizli butik satışlarından ve VIP davetlerden ilk siz haberdar olun.',
    'footer.emailPlaceholder': 'E-POSTA ADRESİNİZ',
    'footer.subscribeSuccess': 'Özel listemize başarıyla kaydoldunuz. VIP ayrıcalıklar yakında e-postanızda.',
    'footer.subscribeError': 'Bir hata oluştu. Lütfen daha sonra tekrar deneyin.',
    'footer.copyright': '© 2026 PEONY COLLECTIVE. BÜTÜN HAKLARI SAKLIDIR. MIRASIN DİJİTAL SAHİBİ.',
    'footer.authenticity': 'Orijinallik Garantisi',
    'footer.labApproved': 'Peony Lab™ Onaylı',
    'footer.insuredDelivery': 'VIP Sigortalı Teslimat',
    'footer.securePayment': 'GÜVENLİ ÖDEME:',
    'howItWorks.headerTag': 'TRUST INFRASTRUCTURE',
    'howItWorks.headerTitle': 'Lüksün Yeni',
    'howItWorks.headerTitleSub': 'Güven Standartı',
    'howItWorks.headerSub': 'Yarım milyonluk bir yatırım yaparken riskleri biz üstleniyoruz. Peony Lab ile her işlem, kurumsal güvence altındadır.',
    'howItWorks.stepLabel': 'Adım',
    'howItWorks.step1Title': 'Güvenli Ödeme & Rezervasyon',
    'howItWorks.step1Desc': 'Alıcı ödemeyi yapar, ancak para satıcıya gitmez. Peony\'nin güvenli emanet havuzunda (Escrow) bloke edilir.',
    'howItWorks.step2Title': 'Peony Lab\'e Gönderim',
    'howItWorks.step2Desc': 'Satıcı, ürünü incelenmek üzere özel kurye ile İstanbul\'daki onay merkezimize (The Lab) gönderir.',
    'howItWorks.step3Title': '32 Noktalı Ekspertiz & Makroskobik Tarama',
    'howItWorks.step3Desc': 'Uzmanlarımız derinin dikişinden, donanım ağırlığına kadar ürünü fiziksel olarak inceler ve global referans veritabanımızla karşılaştırır.',
    'howItWorks.step4Title': 'Dijital Pasaport & Teslimat',
    'howItWorks.step4Desc': 'Ürün onaylanırsa, NFC özellikli Dijital Pasaportu ile mühürlenir ve alıcıya sigortalı olarak gönderilir. Para satıcıya geçer.',
    'howItWorks.labTitle': 'Peony Lab™',
    'howItWorks.labDesc': 'Fiziksel onay merkezimiz, Türkiye\'nin ilk ve tek lüks çanta ekspertiz laboratuvarıdır. 3D tarama teknolojisi ve spektral analiz ile deri gözeneklerine kadar iniyoruz.',
    'howItWorks.labFeature1': 'Sertifikalı Ekspertiz Heyeti',
    'howItWorks.labFeature2': 'Mikroskobik Dikiş Analizi',
    'cart.title': 'SEPETİM',
    'cart.empty': 'Sepetinizde henüz ürün bulunmamaktadır.',
    'cart.subtotal': 'Ara Toplam',
    'cart.checkout': 'ÖDEMEYE GEÇ',
    'cart.shippingInfo': 'Tüm gönderiler VIP Sigortalı & Peony Lab Sertifikalıdır.',
    'product.inCart': 'SEPETTE',
    'product.sellerInfo': 'SATICI BİLGİSİ',
    'product.guarantee': '%100 Orijinallik Garantisi & Peony Lab Sertifikası',
    'product.shippingTime': 'İstanbul içi aynı gün VIP kurye veya 24 saatte kargo.',
    'notif.title': 'BİLDİRİMLER',
    'notif.clear': 'Temizle',
    'notif.empty': 'Henüz bildirim bulunmuyor.',
    'search.placeholder': 'ARAMAYA BAŞLAYIN...',
    'search.results': 'Arama Sonuçları',
    'search.searching': 'Aranıyor...',
    'search.notFound': 'ile eşleşen seçkin bir parça bulunamadı.',
    'search.popular': 'Popüler Aramalar',
    'settings.title': 'Kişisel Bilgiler & Ödemeler',
    'settings.phone': 'Telefon Numarası',
    'settings.iban': 'IBAN (Ödemeleriniz İçin)',
    'settings.marketplace': 'Pazaryeri (Satıcı) Bilgileri',
    'settings.accountType': 'Hesap Tipi',
    'settings.individual': 'Bireysel (Şahıs)',
    'settings.corporate': 'Kurumsal (Şirket)',
    'settings.tckn': 'TC Kimlik No (Bireysel)',
    'settings.vkn': 'Vergi No (Kurumsal)',
    'settings.companyTitle': 'Firma Ünvanı (Kurumsal)',
    'settings.deliveryAddress': 'Teslimat Adresim',
    'settings.defaultAddress': 'Varsayılan Adres',
    'settings.updateBtn': 'Bilgileri Güncelle',
    'settings.updating': 'Güncelleniyor...',
    'settings.changeAvatar': 'Değiştir',
    'settings.approvedMember': 'Onaylı Üye & Koleksiyoner',
    'msg.conversations': 'Görüşmelerim',
    'msg.noConversations': 'Henüz bir mesajlaşma kaydı bulunmuyor.',
    'msg.activeConversation': 'Aktif Görüşme',
    'msg.safetyNotice': 'Güvenliğiniz için telefon numarası, e-posta veya harici link paylaşmayınız.',
    'msg.safetyBadge': 'Peony Güvencesi',
    'msg.placeholder': 'Mesajınızı buraya yazın...',
    'msg.selectPrompt': 'Sohbet seçin veya bir satıcı ile konuşma başlatın.',
    'msg.hiddenContact': '[İLETİŞİM BİLGİSİ GİZLENDİ]',
    'concierge.sub': 'VIP DESTEK & TEKLİF HATTI',
    'concierge.welcome': 'Merhaba, ben Peony VIP Danışmanınız. Seçkin koleksiyonumuz ve hizmetlerimizle ilgili size nasıl yardımcı olabilirim?',
    'concierge.museBtn': 'Peony Muse Stil Sohbeti',
    'concierge.newBadge': 'YENİ',
    'concierge.spectralBtn': '3D Spektral Orijinallik Sorgula',
    'concierge.offerBtn': 'Özel VIP Teklif Ver (100K+)',
    'concierge.liveChatBtn': 'Temsilci ile Canlı Görüş',
    'concierge.labTitle': 'Peony Lab™ Güvencesi',
    'concierge.labP1': 'Sistemimizdeki tüm arşiv parçaları 32 noktalı fiziksel inceleme ve 3D Spektral Analizden geçirilmektedir.',
    'concierge.labP2': 'İlgilendiğiniz ürünün sayfasında bulunan "Dijital Pasaportu Görüntüle" butonuna tıklayarak laboratuvar raporunu, orijinallik puanını ve blokzincir kontrat kayıtlarını canlı olarak inceleyebilirsiniz.',
    'concierge.backMenu': '← Ana Menüye Dön',
    'concierge.backToMenu': '← Menüye Dön',
    'concierge.cancel': '← İptal Et',
    'concierge.offerFormTitle': 'VIP ÖZEL TEKLİF FORMU',
    'concierge.placeholderName': 'ADINIZ SOYADINIZ',
    'concierge.placeholderContact': 'İLETİŞİM (E-POSTA VEYA TELEFON)',
    'concierge.placeholderProduct': 'İLGİLENDİĞİNİZ ÜRÜN (örn: Rolex Kermit)',
    'concierge.placeholderOffer': 'TEKLİFİNİZ (örn: 450.000 ₺)',
    'concierge.submitOffer': "Teklifi Concierge'e İlet",
    'concierge.offerSuccessTitle': 'Teklifiniz Alındı',
    'concierge.great': 'Harika',
    'concierge.whatsappDesc': 'VIP Satış Danışmanlarımızla doğrudan görüşmek, canlı görsel talep etmek ya da özel kurye randevusu oluşturmak için lütfen Concierge hattımızla iletişime geçin.',
    'concierge.openWhatsapp': "WhatsApp'ı Aç",
    'concierge.museWelcome': 'Merhaba ben Peony stil küratörünüz Muse. Bugün nereyi ziyaret edeceksiniz veya nasıl bir davete katılacaksınız? Size oranın havasına ve dokusuna en uygun lüks parçaları önereyim.',
    'concierge.musePlaceholder': 'Bugün nereye gidiyorsunuz?',
    'concierge.ask': 'SOR',
    'concierge.curatorPicks': 'Küratörün Seçtikleri:',
    'footer.companyAddress': 'Adres: Merkez Mah. Üsküdar Cad. No: 57 İç Kapı No: 1, 34788 Çekmeköy/İstanbul',
    'footer.companyPhone': 'Telefon: +90 (552) 365 20 93 | E-posta: info@peonycollective.com',
    'footer.companyTax': 'Vergi No: 8590652178 (Sarıgazi Vergi Dairesi)',
    'dash.collectorTitle': 'Koleksiyon Panelim',
    'dash.curatorTitle': 'Mağaza Terminali',
    'dash.totalSpend': 'Toplam Harcama',
    'dash.allTime': 'Tüm zamanlar',
    'dash.itemsOwned': 'Sahip Olunan Parça',
    'dash.inCollection': 'Koleksiyonunuzda',
    'dash.activeOrders': 'Aktif Siparişler',
    'dash.onTheWay': 'Teslimat aşamasında',
    'dash.collectorActive': 'Koleksiyoner Üyeliği Aktif',
    'dash.totalEarnings': 'Toplam Kazanç',
    'dash.completedSales': 'Tamamlanan satışlar',
    'dash.activeListings': 'Aktif İlanlar',
    'dash.inMarket': 'Piyasada bekliyor',
    'dash.pendingApproval': 'Onay Bekliyor',
    'dash.labInspecting': 'Peony Lab inceliyor',
    'dash.soldItems': 'Satılan Ürün',
    'dash.inventory': 'Envanter',
    'dash.addNewProduct': 'Yeni Ürün Ekle',
    'dash.stepPaid': 'Ödeme Alındı',
    'dash.stepLab': "Lab'a Yolda",
    'dash.stepInspect': 'İnceleniyor',
    'dash.stepApprove': 'Onaylandı',
    'dash.stepShipping': 'Kargoda',
    'dash.stepDelivered': 'Teslim Edildi',
    'popup.badge': 'PREMIUM İKİNCİ EL',
    'popup.titleLine1': 'Dolabınızdaki',
    'popup.titleLine2': 'Lüksü Nakde Çevirin',
    'popup.desc': 'Kullanmadığınız tasarımcı çantalarınızı, kıyafetlerinizi veya ayakkabılarınızı Peony Collective güvencesiyle hemen satın. Süreci biz yönetelim, kazanç hesabınıza yatsın.',
    'popup.startSelling': 'HEMEN SATIŞA BAŞLA',
    'popup.later': 'DAHA SONRA'
  },
  en: {
    'topbar.announcement': '✦ 100% VERIFIED AUTHENTICITY & SAME-DAY CONCIERGE DELIVERY IN ISTANBUL',
    'topbar.announcement1': '✦ 100% PHYSICAL APPRAISAL & 3D SPECTRAL ANALYSIS GUARANTEE',
    'topbar.announcement2': '⚡ 4-HOUR EXPRESS VIP COURIER DELIVERY IN ISTANBUL',
    'topbar.announcement3': '🛡️ PEONY LAB™ CERTIFIED & LEGALLY PROTECTED ARCHIVE COLLECTION',
    'topbar.vipBadge': 'PEONY CONCIERGE™',
    'topbar.whatsapp': 'VIP CLIENT ADVISOR',
    'nav.howItWorks': 'HOW IT WORKS',
    'nav.myPanel': 'MY DASHBOARD',
    'nav.myOrders': 'MY ORDERS',
    'nav.sell': 'CONSIGN WITH US',
    'nav.myAccount': 'MY ACCOUNT',
    'nav.login': 'LOG IN',
    'nav.logout': 'LOG OUT',
    'nav.allProducts': 'ALL PRODUCTS',
    'nav.women': 'WOMEN',
    'nav.men': 'MEN',
    'nav.kids': 'KIDS',
    'nav.accessories': 'ACCESSORIES',
    'nav.newArrivals': 'NEW ARRIVALS',
    'nav.collection': 'Collection',
    'nav.cart': 'Cart',
    'nav.addToCart': 'ADD TO CART',
    'nav.vipOffers': 'VIP Offers',
    'nav.brands': 'BRANDS',
    'nav.userServices': 'CLIENT SERVICES',
    'nav.account': 'ACCOUNT',
    'nav.messages': 'MY MESSAGES',
    'nav.settings': 'ACCOUNT SETTINGS',
    'hero.title': 'CURATED CIRCULAR LUXURY',
    'hero.subtitle': 'Expert-appraised, 100% verified authentic secondhand luxury archive pieces.',
    'hero.explore': 'EXPLORE COLLECTION',
    'hero.consign': 'CONSIGN YOUR LUXURY',
    'hero.tagline': 'CURATORS OF HERITAGE',
    'category.bags': 'Bags',
    'category.clothing': 'Clothing',
    'category.shoes': 'Shoes',
    'category.accessories': 'Accessories',
    'category.outerwear': 'Outerwear',
    'category.topwear': 'Tops',
    'category.bottomwear': 'Bottoms',
    'category.dress': 'Dresses',
    'category.girls': 'Girls',
    'category.boys': 'Boys',
    'category.scarf': 'Scarves',
    'category.bracelet': 'Bracelets',
    'category.foulard': 'Foulards',
    'category.hat': 'Hats',
    'category.belt': 'Belts',
    'category.glasses': 'Eyewear',
    'category.wallet': 'Wallets',
    'category.jewelry': 'Jewelry',
    'product.buy': 'BUY NOW',
    'product.offer': 'MAKE AN OFFER',
    'product.sold': 'THIS ITEM IS SOLD',
    'product.condition': 'CONDITION',
    'product.year': 'PURCHASE YEAR',
    'product.seller': 'SELLER',
    'product.dimensions': 'DIMENSIONS',
    'product.expertReport': 'PEONY EXPERT REPORT',
    'weather.title': '📍 PEONY WEATHER CONCIERGE',
    'weather.subtitle': 'Personalized Local Style Recommendations',
    'manifesto.title': 'You are passing on a heritage, not just a product.',
    'manifesto.desc': 'At Peony Collective, luxury is not just a label, but a promise. With our expert curators and lab-grade appraisal process, authenticity is guaranteed.',
    'metric.portfolioValue': 'Portfolio Value',
    'metric.portfolioSub': 'Verified & Pending',
    'metric.counterfeit': 'Counterfeit Rate',
    'metric.counterfeitSub': 'Since Day One',
    'metric.controlPoints': 'Checkpoints',
    'metric.controlSub': 'Physical Appraisal',
    'metric.approval': 'Avg. Approval',
    'metric.approvalSub': 'Fast Processing Time',
    'metric.hours': 'HRS',
    'curated.seasonal': 'Seasonal Curation',
    'curated.smart': 'Smart Luxury (Under 15,000 ₺)',
    'curated.summerTitle': 'Summer Curation: Harmony of Contrasts',
    'curated.summerDesc': 'Luxury merges everyday comfort with the pinnacle of desire. From stylish slides on the beach to sophisticated Kelly bags at evening galas.',
    'curated.explore': 'Explore Curation →',
    'home.shopByCategory': 'Shop by Category',
    'home.allCollection': 'ALL COLLECTION',
    'home.beachVibe': 'BEACH VIBE ⛵',
    'home.cityBreeze': 'CITY BREEZE 🏙️',
    'home.eveningEvent': 'EVENING EVENT 🍸',
    'home.allGenders': 'ALL GENDERS',
    'home.allBrands': 'ALL BRANDS',
    'trust.standards': 'PEONY STANDARDS',
    'trust.title': 'Trust Chain & Appraisal',
    'trust.tabHow': 'HOW IT WORKS',
    'trust.tabLab': 'PEONY LAB & ENTRUPY',
    'trust.tabCert': 'CERTIFICATE OF AUTHENTICITY',
    'trust.tabStories': 'STORY OF OBJECTS',
    'trust.step1Title': 'Consignor Submits',
    'trust.step1Desc': 'Snaps photos and uploads to platform. Receives instant valuation.',
    'trust.step2Title': 'Escrow & Courier',
    'trust.step2Desc': 'Payment is secured in escrow. VIP courier retrieves item from seller.',
    'trust.step3Title': 'Lab Inspection',
    'trust.step3Desc': '32-point physical audit + Entrupy AI technology verification.',
    'trust.step4Title': 'Delivery & Payout',
    'trust.step4Desc': 'Verified item reaches buyer, payout released to seller.',
    'partner.tagline': 'PARTNER WITH PEONY',
    'partner.title': 'Turn Luxury Into Liquidity',
    'partner.tabSupplier': 'FOUNDING SUPPLIER PROGRAM (0%)',
    'partner.tabVip': 'PEONY VIP (CONCIERGE)',
    'partner.launchTag': 'SPECIAL LAUNCH ADVANTAGE',
    'partner.commissionTitle': 'Commission Rates Starting from 0%',
    'partner.commissionDesc': 'Join as a founding supplier during Peony launch phase; liquidate your luxury items with maximum value and 0% commission benefits.',
    'partner.applyBtn': 'APPLY NOW',
    'partner.treasureTag': 'UNLOCK YOUR WARDROBE\'S VALUE',
    'partner.treasureTitle': 'Unused luxury in your closet is a treasure for someone else.',
    'partner.sellNowBtn': 'START SELLING NOW',
    'footer.tagline': 'Curators of Luxury Heritage',
    'footer.aboutText': 'Never leave a half-million investment to chance. Peony Collective verifies every piece through 32-point physical appraisal and 3D Spectral Analysis.',
    'footer.legalTitle': 'LEGAL DOCUMENTS',
    'footer.terms': 'Terms of Use',
    'footer.privacy': 'Privacy Policy',
    'footer.kvkk': 'Data Protection (KVKK)',
    'footer.distanceSales': 'Distance Sales Agreement',
    'footer.preInfo': 'Preliminary Information',
    'footer.returnPolicy': 'Return Policy',
    'footer.delivery': 'Shipping & Delivery',
    'footer.privateListTitle': 'PRIVATE LIST',
    'footer.privateListDesc': 'Be the first to access private curations, secret drops, and VIP invitations.',
    'footer.emailPlaceholder': 'YOUR EMAIL ADDRESS',
    'footer.subscribeSuccess': 'You have joined our private list. VIP privileges will reach your inbox soon.',
    'footer.subscribeError': 'An error occurred. Please try again later.',
    'footer.copyright': '© 2026 PEONY COLLECTIVE. ALL RIGHTS RESERVED. CURATORS OF HERITAGE.',
    'footer.authenticity': '100% Authenticity Guarantee',
    'footer.labApproved': 'Peony Lab™ Verified',
    'footer.insuredDelivery': 'VIP Insured Delivery',
    'footer.securePayment': 'SECURE PAYMENT:',
    'howItWorks.headerTag': 'TRUST INFRASTRUCTURE',
    'howItWorks.headerTitle': 'The New Standard of',
    'howItWorks.headerTitleSub': 'Luxury Trust',
    'howItWorks.headerSub': 'When making a high-value luxury investment, we absorb the risk. Every transaction is backed by Peony Lab enterprise guarantees.',
    'howItWorks.stepLabel': 'Step',
    'howItWorks.step1Title': 'Secure Payment & Escrow',
    'howItWorks.step1Desc': 'Buyer completes payment, which is held in Peony\'s secure Escrow vault rather than sent directly to the seller.',
    'howItWorks.step2Title': 'Shipment to Peony Lab',
    'howItWorks.step2Desc': 'Seller dispatches item via dedicated courier to our Istanbul authentication center (The Lab).',
    'howItWorks.step3Title': '32-Point Appraisal & Macroscopic Scan',
    'howItWorks.step3Desc': 'Our experts physically inspect every detail from leather grain to hardware weight against our global reference database.',
    'howItWorks.step4Title': 'Digital Passport & Delivery',
    'howItWorks.step4Desc': 'Once verified, item is sealed with an NFC Digital Passport and shipped insured to buyer. Funds are released to seller.',
    'howItWorks.labTitle': 'Peony Lab™',
    'howItWorks.labDesc': 'Our physical authentication center is Turkey\'s first specialized luxury handbag appraisal lab using 3D scanning and spectral analysis.',
    'howItWorks.labFeature1': 'Certified Appraisal Committee',
    'howItWorks.labFeature2': 'Microscopic Stitching Analysis',
    'cart.title': 'MY CART',
    'cart.empty': 'Your cart is currently empty.',
    'cart.subtotal': 'Subtotal',
    'cart.checkout': 'PROCEED TO CHECKOUT',
    'cart.shippingInfo': 'All shipments are VIP Insured & Peony Lab Certified.',
    'product.inCart': 'IN CART',
    'product.sellerInfo': 'SELLER INFORMATION',
    'product.guarantee': '100% Authenticity Guarantee & Peony Lab Certification',
    'product.shippingTime': 'Same-day VIP courier delivery in Istanbul or shipping within 24 hours.',
    'notif.title': 'NOTIFICATIONS',
    'notif.clear': 'Clear',
    'notif.empty': 'No notifications yet.',
    'search.placeholder': 'START SEARCHING...',
    'search.results': 'Search Results',
    'search.searching': 'Searching...',
    'search.notFound': 'No matching luxury pieces found for',
    'search.popular': 'Popular Searches',
    'settings.title': 'Personal Info & Payments',
    'settings.phone': 'Phone Number',
    'settings.iban': 'IBAN (For Payouts)',
    'settings.marketplace': 'Marketplace (Seller) Info',
    'settings.accountType': 'Account Type',
    'settings.individual': 'Individual',
    'settings.corporate': 'Corporate (Company)',
    'settings.tckn': 'National ID (TCKN)',
    'settings.vkn': 'Tax Number (VKN)',
    'settings.companyTitle': 'Company Title',
    'settings.deliveryAddress': 'Shipping Address',
    'settings.defaultAddress': 'Default Address',
    'settings.updateBtn': 'Update Information',
    'settings.updating': 'Updating...',
    'settings.changeAvatar': 'Change',
    'settings.approvedMember': 'Verified Member & Collector',
    'msg.conversations': 'My Conversations',
    'msg.noConversations': 'No message records found yet.',
    'msg.activeConversation': 'Active Conversation',
    'msg.safetyNotice': 'For your security, do not share phone numbers, emails, or external links.',
    'msg.safetyBadge': 'Peony Protection',
    'msg.placeholder': 'Type your message here...',
    'msg.selectPrompt': 'Select a chat or start a conversation with a seller.',
    'msg.hiddenContact': '[CONTACT INFORMATION HIDDEN]',
    'concierge.sub': 'VIP CLIENT ADVISOR & OFFERS',
    'concierge.welcome': 'Hello, I am your Peony VIP Client Advisor. How may I assist you with our curated archive collection and services today?',
    'concierge.museBtn': 'Peony Muse Style Chat',
    'concierge.newBadge': 'NEW',
    'concierge.spectralBtn': '3D Spectral Authenticity Check',
    'concierge.offerBtn': 'Make Special VIP Offer (100K+)',
    'concierge.liveChatBtn': 'Live Chat with Client Advisor',
    'concierge.labTitle': 'Peony Lab™ Guarantee',
    'concierge.labP1': 'Every archive piece in our system is verified through 32-point physical inspection and 3D Spectral Analysis.',
    'concierge.labP2': 'You can review live lab reports, authenticity scores, and blockchain contract records by clicking "View Digital Passport" on any product page.',
    'concierge.backMenu': '← Back to Main Menu',
    'concierge.backToMenu': '← Back to Menu',
    'concierge.cancel': '← Cancel',
    'concierge.offerFormTitle': 'VIP SPECIAL OFFER FORM',
    'concierge.placeholderName': 'YOUR FULL NAME',
    'concierge.placeholderContact': 'CONTACT (EMAIL OR PHONE)',
    'concierge.placeholderProduct': 'ITEM OF INTEREST (e.g. Rolex Kermit)',
    'concierge.placeholderOffer': 'YOUR OFFER (e.g. $12,500)',
    'concierge.submitOffer': 'Submit Offer to Concierge',
    'concierge.offerSuccessTitle': 'Offer Received',
    'concierge.great': 'Great',
    'concierge.whatsappDesc': 'To speak directly with our VIP Client Advisors, request live photos, or schedule a dedicated concierge courier appointment, please contact our Concierge line.',
    'concierge.openWhatsapp': 'Open WhatsApp',
    'concierge.museWelcome': 'Hello, I am Muse, your Peony style curator. Where are you visiting today or what kind of event are you attending? Let me recommend the finest luxury pieces perfectly tailored to the vibe.',
    'concierge.musePlaceholder': 'Where are you heading today?',
    'concierge.ask': 'ASK',
    'concierge.curatorPicks': "Curator's Picks:",
    'footer.companyAddress': 'Address: Merkez Mah. Üsküdar Cad. No: 57 İç Kapı No: 1, 34788 Çekmeköy/Istanbul, Turkey',
    'footer.companyPhone': 'Phone: +90 (552) 365 20 93 | Email: info@peonycollective.com',
    'footer.companyTax': 'Tax No: 8590652178 (Sarigazi Tax Office)',
    'dash.collectorTitle': 'My Collection Dashboard',
    'dash.curatorTitle': 'Store Terminal',
    'dash.totalSpend': 'Total Spend',
    'dash.allTime': 'All time',
    'dash.itemsOwned': 'Items Owned',
    'dash.inCollection': 'In your collection',
    'dash.activeOrders': 'Active Orders',
    'dash.onTheWay': 'In delivery pipeline',
    'dash.collectorActive': 'Collector Membership Active',
    'dash.totalEarnings': 'Total Earnings',
    'dash.completedSales': 'Completed sales',
    'dash.activeListings': 'Active Listings',
    'dash.inMarket': 'Listed in market',
    'dash.pendingApproval': 'Pending Approval',
    'dash.labInspecting': 'Peony Lab reviewing',
    'dash.soldItems': 'Sold Items',
    'dash.inventory': 'Inventory',
    'dash.addNewProduct': 'Add New Product',
    'dash.stepPaid': 'Payment Received',
    'dash.stepLab': 'In Transit to Lab',
    'dash.stepInspect': 'Under Inspection',
    'dash.stepApprove': 'Approved',
    'dash.stepShipping': 'Shipped',
    'dash.stepDelivered': 'Delivered',
    'popup.badge': 'PREMIUM PRE-OWNED',
    'popup.titleLine1': 'Turn Your Closet',
    'popup.titleLine2': 'Luxury Into Cash',
    'popup.desc': 'Sell your unused designer bags, clothing, or shoes with Peony Collective guarantee. We manage the process and send your earnings straight to your account.',
    'popup.startSelling': 'START SELLING NOW',
    'popup.later': 'MAYBE LATER'
  }
}

export function SettingsProvider({ children }: { children: ReactNode }) {
  const [currency, setCurrencyState] = useState<Currency>('TRY')
  const [language, setLanguageState] = useState<Language>('tr')
  const [rates, setRates] = useState<Rates>(defaultRates)

  useEffect(() => {
    // Load currency and language preferences from localStorage
    const savedCurrency = localStorage.getItem('peony_currency') as Currency
    if (savedCurrency && ['TRY', 'USD', 'EUR'].includes(savedCurrency)) {
      setCurrencyState(savedCurrency)
    }

    const savedLang = localStorage.getItem('peony_lang') as Language
    if (savedLang && ['tr', 'en'].includes(savedLang)) {
      setLanguageState(savedLang)
    }

    // Fetch live exchange rates
    fetch('/api/exchange-rates')
      .then(res => res.json())
      .then(data => {
        if (data.success && data.rates) {
          setRates(data.rates)
        }
      })
      .catch(err => console.error('SettingsProvider exchange rate load error:', err))
  }, [])

  const setCurrency = (c: Currency) => {
    setCurrencyState(c)
    localStorage.setItem('peony_currency', c)
  }

  const setLanguage = (l: Language) => {
    setLanguageState(l)
    localStorage.setItem('peony_lang', l)
    document.documentElement.lang = l
  }

  const formatPrice = (priceInTry: number): string => {
    if (!priceInTry || isNaN(priceInTry)) return '0 ₺'

    if (currency === 'USD') {
      const converted = Math.round(priceInTry / (rates.USD || 38.5))
      return `$ ${converted.toLocaleString('en-US')}`
    }

    if (currency === 'EUR') {
      const converted = Math.round(priceInTry / (rates.EUR || 42.0))
      return `€ ${converted.toLocaleString('de-DE')}`
    }

    return `${priceInTry.toLocaleString('tr-TR')} ₺`
  }

  const t = (key: string, defaultText?: string): string => {
    const langDict = translations[language] || translations.tr
    return langDict[key] || defaultText || key
  }

  return (
    <SettingsContext.Provider value={{
      currency,
      setCurrency,
      language,
      setLanguage,
      rates,
      formatPrice,
      t
    }}>
      {children}
    </SettingsContext.Provider>
  )
}

export function useSettings() {
  const context = useContext(SettingsContext)
  if (!context) {
    return {
      currency: 'TRY' as Currency,
      setCurrency: () => {},
      language: 'tr' as Language,
      setLanguage: () => {},
      rates: defaultRates,
      formatPrice: (p: number) => `${(p || 0).toLocaleString('tr-TR')} ₺`,
      t: (k: string, d?: string) => d || k
    }
  }
  return context
}
